name: rick_and_morty
description: Rick and Morty characters library 

publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  retrofit: ^4.0.1
  freezed_annotation: ^2.2.0
  get_it: ^7.6.0
  injectable: ^2.1.2
  go_router: ^8.0.0
  dio: ^5.2.0+1
  mocktail: ^0.3.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^2.4.5
  flutter_lints: ^2.0.0
  freezed: ^2.3.5
  json_serializable: ^6.7.0
  injectable_generator: ^2.1.6
  retrofit_generator: ^7.0.1

flutter:
  uses-material-design: true
